data:
  data_dir: "/public/wjzhang/datasets/PLU_AUT_sample1024_xyzlbs.h5"
  batch_size: 32
  num_workers: 4
  val_split: 0.1

model:
  num_classes: 9
  model_type: "pointnet"

optimizer:
  learning_rate: 0.0003
  weight_decay: 0.00005
  max_epochs: 50
  eta_min: 0.000001
  warmup_epochs: 5
trainer:
  max_epochs: 50
  accelerator: "gpu"
  devices: [1]
  log_every_n_steps: 1
  enable_checkpointing: True
  precision: 32
  default_root_dir: "Results/"

comet:
  project: "treespecies-cls"
  name: "pointnet-baseline"
  offline_directory: "Results/comet_logs"
