data:
  data_dir: "/public/wjzhang/datasets/PLU_AUT_sample1024_xyzlbs.h5"
  batch_size: 32
  num_workers: 4
  val_split: 0.1

model:
  num_classes: 9
  learning_rate: 0.001
  model_type:"pointnet"
  
trainer:
  max_epochs: 50
  accelerator: "gpu"
  devices: [1]
  log_every_n_steps: 1
  enable_checkpointing: True
  precision: 32
  default_root_dir: "Results/"

wandb:
  project: "pointnet-classification"
  name: "pointnet-baseline"
  group: "pointnet"
  tags: ["v1", "xyz"]
  entity: "zwjnefu"
  save_dir: "wandb_logs"
  log_model: "all"
  offline: false