data:
  hdf5_path: "data/your_pointcloud_data.h5"
  batch_size: 32
  num_workers: 4
  val_split: 0.1

model:
  num_classes: 8
  learning_rate: 1e-3

trainer:
  max_epochs: 20
  accelerator: auto
  devices: auto
  log_every_n_steps: 10
  enable_checkpointing: True
  precision: 32
  default_root_dir: "experiments/"
