defaults:
  - base_pointnet
  - _self_
data:
  batch_size: 32
  num_workers: 4
  val_split: 0.1
  data_dir: "/public/wjzhang/datasets/PLU_AUT_sample1024_xyzlbs_5fold.h5"
  augmentations_list: ['rotate', 'scale', 'shift']

model:
  num_classes: 9
  model_type: "pointnet"

optimizer:
  learning_rate: 0.001
  weight_decay: 0.00005
  max_epochs: 50
  eta_min: 0.000001
  warmup_epochs: 5

trainer:
  max_epochs: 50
  accelerator: "gpu"
  devices: [1]

comet:
  name: "PLU_AUT_pointnet_lr1e-3_bs32"
  offline_directory: "Results/comet_logs"
